project:
  type: manuscript

manuscript:
  article: FiguresSE.qmd
  code-links: 
    - repo
    - text: "Figure data"
      href: data/SEVizData.csv
      icon: database
  resources:
    - data/SEVizData.csv
    - data/papers.csv
    - GraphErrors.csv
    - GraphTypes.csv


format:
  ieee-pdf: default
  ieee-html: default

notebook-links: false

execute:
  freeze: true



